version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - technews_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - technews_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - technews_network

  celery:
    build: .
    command: celery -A technews worker -l info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db

    networks:
      - technews_network

  celery-beat:
    build: .
    command: celery -A technews beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db
    networks:
      - technews_network

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444"
    networks:
      - technews_network

volumes:
  postgres_data:

networks:
  technews_network:
    driver: bridge

